import AppError from '../../errors/AppError';
import { Prisma } from '../../generated/prisma/client';
import {
  NotificationType,
  PriorityTier,
  ScheduleStatus,
} from '../../generated/prisma/enums';
import { writeAudit } from '../../shared/auditLog';
import prisma from '../../shared/prisma';
import { buildMeta, buildQueryOptions } from '../../shared/queryBuilder';
import { cacheGet, cacheInvalidate, cacheSet } from '../../shared/redis';
import { queueNotifications } from '../notification/notification.service';

const SORTABLE = ['date', 'startTime', 'createdAt'] as const;
const SCHEDULE_CACHE_TTL = 300;

const scheduleSelect = {
  id: true,
  date: true,
  startTime: true,
  endTime: true,
  reason: true,
  status: true,
  isAutoGenerated: true,
  createdAt: true,
  feeder: {
    select: {
      id: true,
      name: true,
      code: true,
      substation: {
        select: {
          id: true,
          name: true,
          zone: { select: { id: true, name: true, code: true } },
        },
      },
    },
  },
} as const;

type TActor = { userId: string; ip: string | null };

/** Priority order used when choosing which feeders to shed first. */
const TIER_WEIGHT: Record<PriorityTier, number> = {
  CRITICAL: 0, // never shed
  HIGH: 1,
  NORMAL: 2,
  LOW: 3,
};

// ---------- CONFLICT DETECTION ----------

/**
 * Two windows overlap when each starts before the other ends. Anything
 * already PLANNED or ACTIVE on the same feeder counts; CANCELLED and
 * COMPLETED rows are historical and may overlap freely.
 */
const findOverlapping = async (
  client: Prisma.TransactionClient | typeof prisma,
  feederId: string,
  startTime: Date,
  endTime: Date,
  excludeId?: string
) =>
  client.loadSheddingSchedule.findFirst({
    where: {
      feederId,
      isDeleted: false,
      status: { in: [ScheduleStatus.PLANNED, ScheduleStatus.ACTIVE] },
      startTime: { lt: endTime },
      endTime: { gt: startTime },
      ...(excludeId ? { id: { not: excludeId } } : {}),
    },
    select: { id: true, startTime: true, endTime: true },
  });

// ---------- MANUAL CREATE ----------

const create = async (
  payload: {
    feederId: string;
    date: string;
    startTime: string;
    endTime: string;
    reason?: string;
  },
  actor: TActor
) => {
  const startTime = new Date(payload.startTime);
  const endTime = new Date(payload.endTime);

  if (endTime <= startTime) {
    throw new AppError(400, 'endTime must be after startTime');
  }

  const feeder = await prisma.feeder.findFirst({
    where: { id: payload.feederId, isDeleted: false },
    select: { id: true, name: true },
  });

  if (!feeder) throw new AppError(404, 'Feeder not found');

  const clash = await findOverlapping(prisma, payload.feederId, startTime, endTime);

  if (clash) {
    throw new AppError(
      409,
      `This feeder already has a schedule from ${clash.startTime.toISOString()} to ${clash.endTime.toISOString()}`
    );
  }

  const schedule = await prisma.loadSheddingSchedule.create({
    data: {
      feederId: payload.feederId,
      date: new Date(payload.date),
      startTime,
      endTime,
      reason: payload.reason,
      createdById: actor.userId,
    },
    select: scheduleSelect,
  });

  await writeAudit(prisma, {
    actorId: actor.userId,
    action: 'SCHEDULE_CREATED',
    entityType: 'LoadSheddingSchedule',
    entityId: schedule.id,
    after: { feederId: payload.feederId, startTime, endTime },
    ipAddress: actor.ip,
  });

  await cacheInvalidate('schedule:*');

  return schedule;
};

// ---------- AUTOMATED PRIORITY-BASED GENERATION ----------

type TGenerateInput = {
  zoneId: string;
  date: string;
  totalDeficitMw: number;
  slotHours?: number;
  startHour?: number;
};

/**
 * Builds a day's load-shedding plan for one zone.
 *
 * Feeders are ranked by the worst (highest) priority tier among the areas
 * they serve: a feeder that supplies even one CRITICAL area (hospital,
 * water pumping) is never shed. The remaining feeders are shed in
 * LOW -> NORMAL -> HIGH order, in consecutive slots, until the requested
 * deficit is covered. Everything is written in one transaction so a
 * partially generated day can never be persisted.
 */
const generate = async (payload: TGenerateInput, actor: TActor) => {
  const slotHours = payload.slotHours ?? 2;
  const startHour = payload.startHour ?? 10;
  const date = new Date(payload.date);

  const zone = await prisma.distributionZone.findFirst({
    where: { id: payload.zoneId, isDeleted: false },
    select: { id: true, name: true },
  });

  if (!zone) throw new AppError(404, 'Distribution zone not found');

  const feeders = await prisma.feeder.findMany({
    where: {
      isDeleted: false,
      substation: { zoneId: payload.zoneId, isDeleted: false },
    },
    select: {
      id: true,
      name: true,
      code: true,
      loadKw: true,
      areas: {
        where: { isDeleted: false },
        select: { id: true, priorityTier: true },
      },
    },
  });

  if (feeders.length === 0) {
    throw new AppError(400, 'This zone has no active feeders to schedule');
  }

  // A feeder inherits the most protective tier among the areas it feeds.
  const ranked = feeders
    .map((feeder) => {
      const worstTier = feeder.areas.reduce<PriorityTier>(
        (worst, area) =>
          TIER_WEIGHT[area.priorityTier] < TIER_WEIGHT[worst]
            ? area.priorityTier
            : worst,
        PriorityTier.LOW
      );
      return { ...feeder, tier: worstTier };
    })
    .filter((feeder) => feeder.tier !== PriorityTier.CRITICAL)
    .sort((a, b) => TIER_WEIGHT[b.tier] - TIER_WEIGHT[a.tier]);

  const protectedCount = feeders.length - ranked.length;

  if (ranked.length === 0) {
    throw new AppError(
      400,
      'Every feeder in this zone serves a CRITICAL area and is exempt from load shedding'
    );
  }

  // Shed feeders until their combined load covers the deficit.
  const deficitKw = payload.totalDeficitMw * 1000;
  const plan: { feederId: string; startTime: Date; endTime: Date; name: string }[] = [];
  let coveredKw = 0;
  let slotIndex = 0;

  for (const feeder of ranked) {
    if (coveredKw >= deficitKw) break;

    const startTime = new Date(date);
    startTime.setUTCHours(startHour + slotIndex * slotHours, 0, 0, 0);
    const endTime = new Date(startTime);
    endTime.setUTCHours(startTime.getUTCHours() + slotHours);

    plan.push({ feederId: feeder.id, startTime, endTime, name: feeder.name });
    coveredKw += feeder.loadKw;
    slotIndex += 1;
  }

  const result = await prisma.$transaction(async (tx) => {
    // Re-check conflicts inside the transaction so a concurrent manual
    // create cannot slip in between planning and writing.
    for (const slot of plan) {
      const clash = await findOverlapping(
        tx,
        slot.feederId,
        slot.startTime,
        slot.endTime
      );

      if (clash) {
        throw new AppError(
          409,
          `Feeder "${slot.name}" already has an overlapping schedule; resolve it before generating`
        );
      }
    }

    await tx.loadSheddingSchedule.createMany({
      data: plan.map((slot) => ({
        feederId: slot.feederId,
        date,
        startTime: slot.startTime,
        endTime: slot.endTime,
        reason: `Auto-generated: ${payload.totalDeficitMw} MW deficit in ${zone.name}`,
        isAutoGenerated: true,
        createdById: actor.userId,
      })),
    });

    const created = await tx.loadSheddingSchedule.findMany({
      where: {
        feederId: { in: plan.map((slot) => slot.feederId) },
        date,
        isAutoGenerated: true,
      },
      select: { id: true, feederId: true, startTime: true, endTime: true },
    });

    // Notify every customer whose meter hangs off an affected feeder.
    const affected = await tx.connection.findMany({
      where: {
        isDeleted: false,
        area: { feederId: { in: plan.map((slot) => slot.feederId) } },
      },
      select: { customerId: true, area: { select: { feederId: true, name: true } } },
    });

    const scheduleByFeeder = new Map(created.map((s) => [s.feederId, s]));

    const notified = await queueNotifications(
      tx,
      affected.map((connection) => {
        const schedule = scheduleByFeeder.get(connection.area.feederId);
        return {
          userId: connection.customerId,
          type: NotificationType.SCHEDULE_PUBLISHED,
          title: 'Load shedding scheduled in your area',
          message: schedule
            ? `${connection.area.name}: power will be off from ${schedule.startTime.toISOString()} to ${schedule.endTime.toISOString()}.`
            : `${connection.area.name}: a load-shedding slot has been scheduled.`,
          scheduleId: schedule?.id ?? null,
        };
      })
    );

    await writeAudit(tx, {
      actorId: actor.userId,
      action: 'SCHEDULE_AUTO_GENERATED',
      entityType: 'DistributionZone',
      entityId: payload.zoneId,
      after: {
        date: payload.date,
        deficitMw: payload.totalDeficitMw,
        slotsCreated: created.length,
      },
      ipAddress: actor.ip,
    });

    return { created, notified };
  });

  await cacheInvalidate('schedule:*');

  return {
    zone: zone.name,
    date: payload.date,
    requestedDeficitMw: payload.totalDeficitMw,
    coveredLoadMw: Number((coveredKw / 1000).toFixed(2)),
    feedersProtected: protectedCount,
    slotsCreated: result.created.length,
    customersNotified: result.notified,
    schedules: result.created,
  };
};

// ---------- READS ----------

const getAll = async (query: Record<string, unknown>) => {
  const { page, limit, skip, sortBy, sortOrder } = buildQueryOptions({
    query,
    sortableFields: SORTABLE,
    defaultSort: 'startTime',
  });

  const where: Prisma.LoadSheddingScheduleWhereInput = {
    isDeleted: false,
    ...(query.feederId ? { feederId: String(query.feederId) } : {}),
    ...(query.status ? { status: query.status as ScheduleStatus } : {}),
    ...(query.date ? { date: new Date(String(query.date)) } : {}),
    ...(query.areaId
      ? { feeder: { areas: { some: { id: String(query.areaId) } } } }
      : {}),
    ...(query.zoneId
      ? { feeder: { substation: { zoneId: String(query.zoneId) } } }
      : {}),
  };

  const [data, total] = await Promise.all([
    prisma.loadSheddingSchedule.findMany({
      where,
      select: scheduleSelect,
      skip,
      take: limit,
      orderBy: { [sortBy]: sortOrder },
    }),
    prisma.loadSheddingSchedule.count({ where }),
  ]);

  return { data, meta: buildMeta(page, limit, total) };
};

/** Upcoming shedding for the areas the caller actually has meters in. */
const getMine = async (userId: string) => {
  const cacheKey = `schedule:user:${userId}:${new Date().toISOString().slice(0, 10)}`;
  const cached = await cacheGet<unknown[]>(cacheKey);
  if (cached) return { data: cached, cached: true };

  const connections = await prisma.connection.findMany({
    where: { customerId: userId, isDeleted: false },
    select: { area: { select: { id: true, name: true, feederId: true } } },
  });

  if (connections.length === 0) {
    return { data: [], cached: false };
  }

  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  const schedules = await prisma.loadSheddingSchedule.findMany({
    where: {
      isDeleted: false,
      feederId: { in: connections.map((c) => c.area.feederId) },
      date: { gte: today },
      status: { in: [ScheduleStatus.PLANNED, ScheduleStatus.ACTIVE] },
    },
    select: scheduleSelect,
    orderBy: { startTime: 'asc' },
    take: 50,
  });

  await cacheSet(cacheKey, schedules, SCHEDULE_CACHE_TTL);

  return { data: schedules, cached: false };
};

const getById = async (id: string) => {
  const schedule = await prisma.loadSheddingSchedule.findFirst({
    where: { id, isDeleted: false },
    select: scheduleSelect,
  });

  if (!schedule) throw new AppError(404, 'Load-shedding schedule not found');

  return schedule;
};

// ---------- STATE TRANSITIONS ----------

const ALLOWED_TRANSITIONS: Record<ScheduleStatus, ScheduleStatus[]> = {
  PLANNED: [ScheduleStatus.ACTIVE, ScheduleStatus.CANCELLED],
  ACTIVE: [ScheduleStatus.COMPLETED, ScheduleStatus.CANCELLED],
  COMPLETED: [],
  CANCELLED: [],
};

const updateStatus = async (id: string, status: ScheduleStatus, actor: TActor) => {
  const existing = await prisma.loadSheddingSchedule.findFirst({
    where: { id, isDeleted: false },
    select: { id: true, status: true },
  });

  if (!existing) throw new AppError(404, 'Load-shedding schedule not found');

  if (!ALLOWED_TRANSITIONS[existing.status].includes(status)) {
    throw new AppError(
      400,
      `Cannot move a ${existing.status} schedule to ${status}. Allowed: ${
        ALLOWED_TRANSITIONS[existing.status].join(', ') || 'none (final state)'
      }`
    );
  }

  const schedule = await prisma.loadSheddingSchedule.update({
    where: { id },
    data: { status },
    select: scheduleSelect,
  });

  await writeAudit(prisma, {
    actorId: actor.userId,
    action: 'SCHEDULE_STATUS_CHANGED',
    entityType: 'LoadSheddingSchedule',
    entityId: id,
    before: { status: existing.status },
    after: { status },
    ipAddress: actor.ip,
  });

  await cacheInvalidate('schedule:*');

  return schedule;
};

const softDelete = async (id: string, actor: TActor) => {
  const existing = await prisma.loadSheddingSchedule.findFirst({
    where: { id, isDeleted: false },
    select: { id: true, status: true },
  });

  if (!existing) throw new AppError(404, 'Load-shedding schedule not found');

  if (existing.status === ScheduleStatus.ACTIVE) {
    throw new AppError(
      409,
      'An ACTIVE schedule cannot be deleted. Cancel or complete it first'
    );
  }

  const schedule = await prisma.loadSheddingSchedule.update({
    where: { id },
    data: { isDeleted: true },
    select: { id: true, status: true, isDeleted: true },
  });

  await writeAudit(prisma, {
    actorId: actor.userId,
    action: 'SCHEDULE_DELETED',
    entityType: 'LoadSheddingSchedule',
    entityId: id,
    before: { isDeleted: false },
    after: { isDeleted: true },
    ipAddress: actor.ip,
  });

  await cacheInvalidate('schedule:*');

  return schedule;
};

export const ScheduleService = {
  create,
  generate,
  getAll,
  getMine,
  getById,
  updateStatus,
  softDelete,
};
